- examples/kitty/Makefile
The default build directory is an absolute path but we forgot about the case where the environment specifies the build dir.
> kitty: pass absolute path of build directory

- components/micropython/lwip_include/arch/cc.h
The MicroPython component uses lwIP for its socket implementation. lwIP in turn makes use of the printf provided by MicroPython. MicroPython's printf does not support the 'h' specifiers, like %hu or %hx. As such, lwIP must not call printf with these specifiers. lwIP's usage of these specifiers can be configured via the U16_F and X16_F constants in lwip_include/arch/cc.h. This commit changes those constants to use %u and %x instead of %hu and %hx.
> micropython: don't use printf 'h' format specifiers

- components/micropython/vfs_fs.c
> Correctly use path buffers when renaming

- ci/kitty.sh
- examples/kitty/Makefile
- examples/kitty/kitty.mk
We no longer check in the images into the repository, so we have an extra `make images` step to fetch them first before calling `make`.
There are probably improvements to be made about how this works in the case you delete your build directory etc.
> examples/kitty: fetch images at build time

- examples/kitty/kitty.system
The I2C data region is currently bound to 262,144 bytes. The request/response regions are currently limited to 20496 bytes. This reflects the sDDF changes to the `NUM_QUEUE_ENTRIES` definition in this pull request: https://github.com/au-ts/sddf/pull/123.
> Use appropriate size for i2c memory regions.

- ci/kitty.sh
- examples/kitty/Makefile
- examples/kitty/kitty.mk
This removes the "make images" build step and allows make to download the images automatically when required.
> kitty: make vm images explicit dependencies

- examples/webserver/webserver.mk
Without this change, the micropython server cannot find the webserver module, as its name is given with respect to the build environment, not the running environment.
> EXEC_MODULE for micropython needs module name, not path

- components/fs/nfs/posix.c
This PR properly enables TCP keep-alive for lwip. Additionally we add proper error checking to the posix layer, where before we were not checking the return value of tcp socket create and assigning bad socket handles.
> Add missing error check in posix TCP handling

- examples/kitty/kitty.mk
- examples/vmm/vmm-dev.mk
- examples/vmm/vmm-virtio-console.mk
- examples/webserver/webserver.mk
There's no reason to my knowledge to always compile without optimisations.
Note that I haven't tested the Kitty or web server example which should be done before merging this.
> examples: always compile with optimisations

- components/fs/nfs/lwip_include/lwipopts.h
- components/micropython/lwip_include/lwipopts.h
Gets rid of these kind of messages in the examples:
```
netif->hwaddr[5]==12 != reply_msg->chaddr[5]==13
netif->hwaddr[5]==12 != reply_msg->chaddr[5]==13
```
which are annoying and don't actually tell you what happened.
The message doesn't mean anything wrong happened and clutter the output.
> Change lwIP minimum warning level to serious

- components/micropython/micropython.c
Not needed anymore. We use the REPL when we want interaction, and EXEC_MODULE when we want a script to automatically run.
> mp: remove unused function

- examples/webserver/webserver.py
When a URL referred to a directory, the webserver is meant to redirect to one with a trailing slash.  However it was returning a relative path, so, for example, https://sel4.org/Foundation/Summit redirected to https://sel4.org/Foundation/Summit/Foundation/summit/
Make it an absolute path.
> Fix directory website redirection

- examples/webserver/webserver.py
Microdot treats a HEAD request as a special case of a GET request. Our
code looks the same for both: we fill out some headers and pass an
async file iterator to Microdot. However, in the case of HEAD request,
Microdot doesn't actually read from the file. The problem is that it
also doesn't close the file. Previously, we opened the file before
passing it to Microdot, so if Microdot didn't close the file then its
handle would leak. This commit changes our code so that we do not open
the file until Microdot actually tries to read from it (because in
that case it will also close it when done reading).
> webserver: fix file handle leak from head request

- components/fs/fat/event.c
- components/fs/nfs/tcp.c
- components/micropython/mpnetworkport.c
- examples/fileio/board/maaxboard/fileio.system
- examples/fileio/board/qemu_virt_aarch64/fileio.system
- examples/fileio/src/config/blk_config.h
- examples/fileio/src/config/ethernet_config.h
- examples/fileio/src/config/serial_config.h
- examples/kitty/src/config/ethernet_config.h
- examples/kitty/src/config/serial_config.h
- examples/webserver/config/ethernet_config.h
- examples/webserver/config/serial_config.h
sDDF renamed `size` to `capacity` in many places; this change fixes the webserver and kitty examples to match so they can use the latest sDDF.
> Size to capacity rename

- components/fs/fat/event.c
- components/micropython/micropython.c
This PR changes how coroutine stack pointers are passed into libmicrokitco's init function. 
Previously it is a variadic function, this is susceptible to programmer error as it is easy to pass in less or more pointers than required and it is not trivial to check how many arguments a variadic function received.
Now it leverages the type system so that the compiler can caught issues statically.
> Libmicrokitco update

- .github/workflows/examples.yaml
- flake.nix
1. remove a bunch of warnings from nix quirks
2. re-add nix examples to CI
3. ~~compiler faster by using the power of *multiprocessors*~~ nevermind
4. make nix not use dependencies from the ambient environment
> various CI + flake fixes

- examples/vmm/Makefile
- examples/vmm/vmm-dev.mk
- examples/vmm/vmm-virtio-console.mk
This PR is an extension of the sDDF PR here (https://github.com/au-ts/sddf/pull/423).
This PR removes all `export override` directives from our makefiles, as discussed here #337.
It was found that `export override` is not syntactically correct in older versions of GNU make, which happen to be the default for MacOS. Also, the variables which it was being applied to were mandatory environment or command line variables, therefore the `export` had no effect.
> Remove export override directives

- .github/workflows/examples.yaml
- ci/examples.sh
- components/fs/fat/fat.mk
- components/fs/nfs/lwip_include/arch/cc.h
- components/fs/nfs/lwip_include/lwipopts.h
- components/fs/nfs/nfs.mk
- components/fs/nfs/tcp.c
- components/micropython/Makefile
- components/micropython/lwip_include/arch/cc.h
- components/micropython/lwip_include/lwipopts.h
- components/micropython/micropython.c
- components/micropython/micropython.mk
- components/micropython/newlibc_stubs.c
- examples/fileio/fileio.mk
- examples/fileio/meta.py
- examples/kitty/kitty.mk
- examples/kitty/meta.py
- examples/vmm/vmm-dev.mk
- examples/vmm/vmm-virtio-console.mk
- examples/webserver/meta.py
- examples/webserver/webserver.mk
- flake.lock
- flake.nix
This PR updates the LionsOS sDDF dependency to the current main. This is in preparation for merging the firewall example into main. It also updates the sdfgen dependency from version 23 to 25.
The sDDF branch is currently set to `lib_sddf_lwip_firewall_features` : https://github.com/au-ts/sddf/pull/480 which will be merged soon. 
The most significant changes to sDDF since the last update are:
- Changes to the lib sDDF LWIP interface (does not effect the existing examples much)
- Creation of a custom `libc`
Since @dumsum is currently working on integrating the changes to how we handle `libc` into LionsOS, this PR just makes the minimal amount of changes necessary to get things buildling. In particular we now:
- Use the custom `libc` in the example make snippet for building sDDF components …
> Update to the latest sDDF

- examples/fileio/fileio.mk
Fix failing build for `fileio` example due to a recent sDDF update that requires the partition schema to be specified in the `mkvirtdisk` script.
> examples/fileio: fix build fail

- components/micropython/mpconfigport.h
Although decreasing the Micropython event hook delay period did not have an impact of the webserver example, it does seem to effect the firewall's Microdot webserver. Not quite sure why, but for the moment its best to revert this change.
> Revert decrease in mp event hook delay period

- examples/firewall/arp/arp_responder.c
- examples/firewall/filters/icmp_filter.c
- examples/firewall/filters/tcp_filter.c
- examples/firewall/filters/udp_filter.c
- examples/firewall/meta.py
- examples/firewall/routing/routing.c
- include/lions/firewall/config.h
The ARP requester and router components are transmitting packets using the IP/MAC address of the firewall interface the packet was received on. They should instead be using the IP/MAC of the interface the packets are being transmitted out of.
> Fix ARP requester and router transmitting with the wrong IP/MAC
